[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.6.0", features = ["openssl"] }
actix-cors = "0.7.0"

openssl = { version = "0.10" }

dotenv = "0.15.0"

serde = { version = "1.0", features = ["derive"] }
