[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.6.0", features = ["openssl"] }
actix-files = "0.6.5"
openssl = { version = "0.10" }
dotenv = "0.15.0"
